---
title: "steam"
author: "Ziyi Bai"
date: "12/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("steamR","tidyverse")
```


```{r}
# Get Game Stats
install.packages("remotes")
remotes::install_github("josegallegos07/steamR")
```

```{r}
# Steam ID 
mykey <- "C73EDDC73DC211B9ED866282677DA606"
game <- steamR::get_schema_stats(steam_key = mykey,app_id = "779340")
```

```{r}
game_stat_df <- data.frame(name=NA,value=NA)[-1,]
for (i in 1:length(game)){
  name <- as.character(game[[i]][3])
  value <- as.numeric(game[[i]][2])
  df_tmp <- cbind.data.frame(name,value)
  game_stat_df <- rbind(game_stat_df,df_tmp)
  game_stat_df <- game_stat_df[!(game_stat_df$name == ""), ]
}
```

## Get Game News
```{r}
# Extract news data
news <- steamR::get_news_for_app(app_id = "779340")
```

```{r}
# Build a dataframe of game news
df_game_news <- data.frame(app_id=NA,title=NA,date=NA,author=NA,content=NA,feed_label=NA,feed_name=NA,urls=NA)[-1,]

for (i in 1:length(news)){
  app_id <- as.character(news[[i]][["appid"]])
  title <- as.character(news[[i]][["title"]])
  date <- as.Date.POSIXct(as.numeric(news[[i]][["date"]]))
  author <- as.character(news[[i]][["author"]])
  content <- as.character(news[[i]][["contents"]])
  feed_label <- as.character(news[[i]][["feedlabel"]])
  feed_name <- as.character(news[[i]][["feedname"]])
  urls <- as.character(news[[i]][["url"]])
  
  df_tmp <- cbind.data.frame(app_id,title,date,author,content,feed_label,feed_name,urls)
  df_game_news <- rbind(df_game_news,df_tmp)
}
```

```{r}
# Clean the text data with regular expression

# Delete the [img] tag
df_game_news$clean_content <- gsub("\\[.*].*\\[/.*]","",df_game_news$content)

# Delete the line breaks
df_game_news$clean_content <- gsub("\n\n|\n","",df_game_news$clean_content)

# Delete the html format
df_game_news$clean_content <- gsub("<[^>]+>","",df_game_news$clean_content)

# Delete the Urls
df_game_news$clean_content <- gsub("(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]", "", df_game_news$clean_content)
```

```{r}
# News dataframe with clean content
df_clean_game_news <- df_game_news %>%
  select(app_id,title,date,author,clean_content,feed_label,feed_name,urls)
```

## Game Achievement
```{r}
# Extract data of achievement
game_achieve <- get_schema_achievements(steam_key = mykey,app_id = "779340")
```

```{r}
# Build a dataframe of game achievement
df_game_achi <- data.frame(achie_name=NA,value=NA,chapter=NA,descrip=NA)[-1,]

for (i in 1:length(game_achieve)){
  achie_name <- as.character(game_achieve[[i]][["name"]])
  value <- as.numeric(game_achieve[[i]][["defaultvalue"]])
  chapter <- as.character(game_achieve[[i]][["displayName"]])
  descrip <- as.character(game_achieve[[i]][["description"]])
  
  df_tmp <- cbind.data.frame(achie_name,value,chapter,descrip)
  df_game_achi <- rbind(df_game_achi,df_tmp)
}
```

```{r}
# Clean the text
df_game_achi$achie_name <- gsub("TK_ACHIEVEMENT_","",df_game_achi$achie_name)

df_game_achi$achie_name <- gsub("_"," ",df_game_achi$achie_name)

df_game_achi$achie_name <- tolower(df_game_achi$achie_name)
```

## Global Achievement Percentage
```{r}
global_achi_percent <- steamR::get_global_achievement_percentages_for_app(app_id = "779340")
```

```{r}
# Build a dataframe of global achievement percentage
df_global_achi <- data.frame(global_achi_name=NA,achi_percent=NA)[-1,]

for (i in 1:length(global_achi_percent)){
  global_achi_name <- 
    as.character(global_achi_percent[[i]][["name"]])
  achi_percent <- 
    as.numeric(global_achi_percent[[i]][["percent"]])
  
  df_tmp <- cbind.data.frame(global_achi_name,achi_percent)
  df_global_achi <- rbind(df_global_achi,df_tmp)
}
```

```{r}
# Clean the text
df_global_achi$global_achi_name <- gsub("TK_ACHIEVEMENT_","",df_global_achi$global_achi_name)

df_global_achi$global_achi_name <- gsub("_"," ",df_global_achi$global_achi_name)

df_global_achi$global_achi_name <- tolower(df_global_achi$global_achi_name)

# Transform the percentage
df_global_achi$achi_percent <- df_global_achi$achi_percent/100
```

# Game Application Info
```{r}
app_list <- steamR::get_app_list()
```

Since the app list is very large, we will take a look at the most recent 100 games.

```{r}
# Build a dataframe of app_list
df_app_list <- data.frame(app_id=NA,game_name=NA)[-1,]
# Get 100 games
for (i in 1:100){
  app_id <- as.character(app_list[[i]][["appid"]])
  game_name <- as.character(app_list[[i]][["name"]])
  
  df_tmp <- cbind.data.frame(app_id,game_name)
  df_app_list <- rbind(df_app_list,df_tmp)
}
```

